// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	endpoint "development-kit/pkg/endpoint"
	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	http1 "net/http"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := mux.NewRouter()
	makeStatusHandler(m, endpoints, options["Status"])
	makeCreateDemoHandler(m, endpoints, options["CreateDemo"])
	makeUpdateDemoHandler(m, endpoints, options["UpdateDemo"])
	makeGetOneDemoHandler(m, endpoints, options["GetOneDemo"])
	makeDeleteDemoHandler(m, endpoints, options["DeleteDemo"])
	return m
}
